# Generated by Django 6.0 on 2025-12-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
